### ISSUE TITLE
Api KEY

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [ChromMob/MineStoreRecode#4]
Hello, I have set up a shop and in the config.yml on the server I have the same API KEY as on the website "https://obchod.agonia.cz/admin/api_access_settings". However, I still get this message in the console: "[19:41:56 INFO]: [MineStore] API KEY is invalid!
[19:42:06 INFO]: [MineStore] API KEY is invalid!"

It puts all the packages normally and it also notifies them correctly. Likewise in the GUI /buy, everything is fine.

Version: MineStore-1.1.7.jar
Server Version: 1.20.4
![image](https://github.com/user-attachments/assets/43c214a8-0111-486a-9747-50e5911abd33)

**Comment by ChromMob** [comment]
Would you mind joining our discord for support: [**DISCORD**](https://discord.com/invite/e8fYVPBgmS).
Fuessing just from the provided info I would say it is because of CLOUDFLARE rate limiting but I can not be sure without proper debug. Due to the nature of the issue of the debug (having to exchange store secrets) I would say its better handled over discord.
